language: php
php:
- '7.2'
- '7.3'
install: composer install

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
- composer test -- --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache